# Generated by Django 5.1.5 on 2026-07-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_employee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_owner",
            field=models.BooleanField(default=True),
        ),
    ]
