# Generated by Django 5.1.5 on 2026-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_backup_codes_user_is_2fa_enabled_user_otp_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="enforce_2fa_owner",
            field=models.BooleanField(default=False),
        ),
    ]
