# Generated by Django 5.1.5 on 2026-07-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_workplace_enforce_2fa_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_admin_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_ce",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workplace",
            name="enforce_2fa_sales",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "관리자(대표)"),
                    ("ADMIN_STAFF", "관리자(사무직원)"),
                    ("SALES", "영업"),
                    ("CE", "CE"),
                ],
                default="CE",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="RoleMenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "관리자(대표)"),
                            ("ADMIN_STAFF", "관리자(사무직원)"),
                            ("SALES", "영업"),
                            ("CE", "CE"),
                        ],
                        max_length=15,
                    ),
                ),
                ("menu_key", models.CharField(max_length=100)),
                ("is_allowed", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_permissions",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "unique_together": {("workplace", "role", "menu_key")},
            },
        ),
    ]
