# Generated by Django 5.1.5 on 2026-07-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_workplace_enforce_2fa_admin_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_invite_accepted",
            field=models.BooleanField(default=True),
        ),
    ]
