# Generated by Django 5.1.5 on 2026-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_invite_code_user_is_invite_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
