# Generated by Django 5.1.5 on 2026-08-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_invite_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        help_text="장비 고유 시리얼 번호", max_length=120, unique=True
                    ),
                ),
                ("model_name", models.CharField(default="복합기 표준 모델", max_length=120)),
                ("customer_name", models.CharField(default="자사 본사", max_length=120)),
                ("location", models.CharField(blank=True, default="사무실", max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "등록 승인"),
                            ("PENDING", "수집 대기"),
                            ("INACTIVE", "비활성"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("count_color", models.IntegerField(default=0)),
                ("count_mono", models.IntegerField(default=0)),
                ("count_large_color", models.IntegerField(default=0)),
                ("count_total", models.IntegerField(default=0)),
                ("monthly_usage_color", models.IntegerField(default=0)),
                ("monthly_usage_mono", models.IntegerField(default=0)),
                ("toner_c", models.IntegerField(default=100)),
                ("toner_m", models.IntegerField(default=100)),
                ("toner_y", models.IntegerField(default=100)),
                ("toner_k", models.IntegerField(default=100)),
                ("drum_k", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printers",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
