# Generated by Django 5.1.5 on 2026-08-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_printerasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCollector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "auth_code",
                    models.CharField(
                        help_text="8자리 수집기 인증 코드 (AST-XXXXXX)", max_length=32, unique=True
                    ),
                ),
                ("agent_token", models.CharField(blank=True, max_length=120, null=True)),
                ("name", models.CharField(default="현장 수집기 Agent", max_length=150)),
                ("customer_name", models.CharField(default="자사 본사", max_length=120)),
                ("ip_range", models.CharField(default="192.168.1.1/24", max_length=100)),
                (
                    "custom_ips",
                    models.JSONField(blank=True, default=list, help_text="수동 지정 IP 목록"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "온라인 (수집중)"),
                            ("OFFLINE", "오프라인 (중단)"),
                            ("PENDING", "인증 대기"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("detected_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectors",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
