# Generated by Django 5.1.5 on 2026-08-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_agentcollector"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterOidMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(default="Fujifilm", help_text="제조사명", max_length=60),
                ),
                (
                    "oid_key",
                    models.CharField(
                        help_text="OID 키 (serial_no, count_color, count_mono, toner_c...)",
                        max_length=60,
                    ),
                ),
                (
                    "oid_value",
                    models.CharField(
                        help_text="SNMP OID 주소 (예: 1.3.6.1.4.1.2988...)", max_length=150
                    ),
                ),
                ("description", models.CharField(blank=True, help_text="설명", max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["vendor_name", "oid_key"],
                "unique_together": {("vendor_name", "oid_key")},
            },
        ),
    ]
