# Generated by Django 5.1.5 on 2026-08-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_printeroidmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidListMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, help_text="제조사", max_length=256, null=True),
                ),
                (
                    "printer_model",
                    models.CharField(
                        blank=True, help_text="프린터 모델", max_length=256, null=True
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, help_text="시리얼번호 OID", max_length=256, null=True
                    ),
                ),
                (
                    "count1",
                    models.CharField(
                        blank=True, help_text="컬러 카운트 OID", max_length=256, null=True
                    ),
                ),
                (
                    "count2",
                    models.CharField(
                        blank=True, help_text="흑백 카운트 OID", max_length=256, null=True
                    ),
                ),
                (
                    "count3",
                    models.CharField(
                        blank=True, help_text="큰컬러 카운트 OID", max_length=256, null=True
                    ),
                ),
                (
                    "count3_k",
                    models.CharField(
                        blank=True, help_text="큰흑백 카운트 OID", max_length=256, null=True
                    ),
                ),
                (
                    "count4",
                    models.CharField(
                        blank=True, help_text="전체 카운트 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_c",
                    models.CharField(
                        blank=True, help_text="시안 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_m",
                    models.CharField(
                        blank=True, help_text="마젠타 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_y",
                    models.CharField(
                        blank=True, help_text="옐로 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_k",
                    models.CharField(
                        blank=True, help_text="블랙 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_k2",
                    models.CharField(
                        blank=True, help_text="블랙2 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_c_max",
                    models.CharField(
                        blank=True, help_text="시안 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_m_max",
                    models.CharField(
                        blank=True, help_text="마젠타 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_y_max",
                    models.CharField(
                        blank=True, help_text="옐로 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_k_max",
                    models.CharField(
                        blank=True, help_text="블랙 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_k2_max",
                    models.CharField(
                        blank=True, help_text="블랙2 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_recovery",
                    models.CharField(
                        blank=True, help_text="회수 토너 OID", max_length=256, null=True
                    ),
                ),
                (
                    "toner_recovery_max",
                    models.CharField(
                        blank=True, help_text="회수 토너 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_c",
                    models.CharField(
                        blank=True, help_text="시안 드럼 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_m",
                    models.CharField(
                        blank=True, help_text="마젠타 드럼 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_y",
                    models.CharField(
                        blank=True, help_text="옐로 드럼 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_k",
                    models.CharField(
                        blank=True, help_text="블랙 드럼 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_c_max",
                    models.CharField(
                        blank=True, help_text="시안 드럼 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_m_max",
                    models.CharField(
                        blank=True, help_text="마젠타 드럼 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_y_max",
                    models.CharField(
                        blank=True, help_text="옐로 드럼 최대값 OID", max_length=256, null=True
                    ),
                ),
                (
                    "drum_k_max",
                    models.CharField(
                        blank=True, help_text="블랙 드럼 최대값 OID", max_length=256, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oid_lists",
            },
        ),
        migrations.CreateModel(
            name="MonitoringPrinter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "license",
                    models.CharField(blank=True, help_text="라이센스", max_length=256, null=True),
                ),
                (
                    "printer_model",
                    models.CharField(
                        blank=True, help_text="프린터 모델명", max_length=256, null=True
                    ),
                ),
                (
                    "scanned_model",
                    models.CharField(
                        blank=True, help_text="스캔된 모델명", max_length=256, null=True
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="장치 유형", max_length=256, null=True),
                ),
                (
                    "contract_type",
                    models.IntegerField(blank=True, help_text="계약 유형", null=True),
                ),
                ("sl", models.CharField(blank=True, help_text="SL", max_length=256, null=True)),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                (
                    "customer_id",
                    models.BigIntegerField(blank=True, help_text="고객사 FK", null=True),
                ),
                (
                    "ip",
                    models.CharField(blank=True, help_text="IP 주소", max_length=256, null=True),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="설치 위치", max_length=256, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        default="active",
                        help_text="상태 (active/inactive/excluded)",
                        max_length=256,
                    ),
                ),
                ("note", models.CharField(blank=True, help_text="비고", max_length=256, null=True)),
                (
                    "installed_time",
                    models.CharField(blank=True, help_text="설치일", max_length=256, null=True),
                ),
                (
                    "contract_start_date",
                    models.CharField(
                        blank=True, help_text="계약 시작일", max_length=256, null=True
                    ),
                ),
                (
                    "contract_end_date",
                    models.CharField(
                        blank=True, help_text="계약 종료일", max_length=256, null=True
                    ),
                ),
                (
                    "operation_company_id",
                    models.BigIntegerField(blank=True, help_text="관리사업자 FK", null=True),
                ),
                (
                    "custom_equipment_model_id",
                    models.BigIntegerField(blank=True, help_text="사용자정의 모델 FK", null=True),
                ),
                (
                    "asset_number",
                    models.BigIntegerField(blank=True, help_text="자산번호", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_printers",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_printers",
                "unique_together": {("workplace", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="PrinterModelMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, help_text="제조사", max_length=256, null=True),
                ),
                (
                    "printer_model",
                    models.CharField(help_text="프린터 모델명", max_length=256, unique=True),
                ),
                (
                    "printer_type",
                    models.IntegerField(blank=True, help_text="프린터 타입", null=True),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, help_text="제품 코드", max_length=256, null=True),
                ),
                ("device_type", models.IntegerField(blank=True, help_text="장치 유형", null=True)),
                ("note", models.TextField(blank=True, help_text="비고", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "oid_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printers",
                        to="accounts.oidlistmaster",
                    ),
                ),
            ],
            options={
                "db_table": "printers",
            },
        ),
        migrations.CreateModel(
            name="SupplyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "customer_id",
                    models.BigIntegerField(blank=True, help_text="고객사 FK", null=True),
                ),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                ("item", models.CharField(help_text="소모품 항목", max_length=256)),
                ("quantity", models.IntegerField(default=1, help_text="수량")),
                (
                    "type",
                    models.CharField(
                        default="manual", help_text="유형 (manual/system)", max_length=256
                    ),
                ),
                (
                    "type_value",
                    models.CharField(blank=True, help_text="유형 값", max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "monitoring_printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_usages",
                        to="accounts.monitoringprinter",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_usages",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "supply_usages",
            },
        ),
        migrations.CreateModel(
            name="MonitoringCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "customer_id",
                    models.BigIntegerField(blank=True, help_text="고객사 FK", null=True),
                ),
                ("employee_count", models.IntegerField(default=0, help_text="종업원 수")),
                ("pc", models.IntegerField(default=0, help_text="PC 대수")),
                ("mfp", models.IntegerField(default=0, help_text="복합기 대수")),
                ("printer", models.IntegerField(default=0, help_text="프린터 대수")),
                ("other_info", models.TextField(blank=True, help_text="기타 정보", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_customers",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_customers",
                "unique_together": {("workplace", "customer_id")},
            },
        ),
        migrations.CreateModel(
            name="MonitoringDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                ("count1", models.IntegerField(default=0)),
                ("count2", models.IntegerField(default=0)),
                ("count3", models.IntegerField(default=0)),
                ("count3_k", models.IntegerField(default=0)),
                ("count4", models.IntegerField(default=0)),
                ("toner_c", models.IntegerField(default=100)),
                ("toner_m", models.IntegerField(default=100)),
                ("toner_y", models.IntegerField(default=100)),
                ("toner_k", models.IntegerField(default=100)),
                ("toner_k2", models.IntegerField(default=100)),
                ("toner_recovery", models.IntegerField(default=100)),
                ("drum_c", models.IntegerField(default=100)),
                ("drum_m", models.IntegerField(default=100)),
                ("drum_y", models.IntegerField(default=100)),
                ("drum_k", models.IntegerField(default=100)),
                ("toner_c_max", models.IntegerField(default=100)),
                ("toner_m_max", models.IntegerField(default=100)),
                ("toner_y_max", models.IntegerField(default=100)),
                ("toner_k_max", models.IntegerField(default=100)),
                ("toner_k2_max", models.IntegerField(default=100)),
                ("toner_recovery_max", models.IntegerField(default=100)),
                ("drum_c_max", models.IntegerField(default=100)),
                ("drum_m_max", models.IntegerField(default=100)),
                ("drum_y_max", models.IntegerField(default=100)),
                ("drum_k_max", models.IntegerField(default=100)),
                ("manufacturer", models.CharField(blank=True, max_length=256, null=True)),
                ("source", models.CharField(default="agent", max_length=256)),
                ("email_updated_at", models.DateTimeField(blank=True, null=True)),
                ("agent_updated_at", models.DateTimeField(blank=True, null=True)),
                ("yyyymmdd", models.CharField(help_text="기준일자 (YYYYMMDD)", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_records",
                        to="accounts.workplace",
                    ),
                ),
                (
                    "monitoring_printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="accounts.monitoringprinter",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_data_records",
                "unique_together": {("monitoring_printer", "yyyymmdd")},
            },
        ),
        migrations.CreateModel(
            name="MonitoringData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                ("count1", models.IntegerField(default=0, help_text="컬러 카운트")),
                ("count2", models.IntegerField(default=0, help_text="흑백 카운트")),
                ("count3", models.IntegerField(default=0, help_text="큰컬러 카운트")),
                ("count3_k", models.IntegerField(default=0, help_text="큰흑백 카운트")),
                ("count4", models.IntegerField(default=0, help_text="전체 카운트")),
                ("toner_c", models.IntegerField(default=100, help_text="시안 토너 잔량")),
                ("toner_m", models.IntegerField(default=100, help_text="마젠타 토너 잔량")),
                ("toner_y", models.IntegerField(default=100, help_text="옐로 토너 잔량")),
                ("toner_k", models.IntegerField(default=100, help_text="블랙 토너 잔량")),
                ("toner_k2", models.IntegerField(default=100, help_text="블랙2 토너 잔량")),
                ("toner_recovery", models.IntegerField(default=100, help_text="회수 토너 잔량")),
                ("drum_c", models.IntegerField(default=100, help_text="시안 드럼 잔량")),
                ("drum_m", models.IntegerField(default=100, help_text="마젠타 드럼 잔량")),
                ("drum_y", models.IntegerField(default=100, help_text="옐로 드럼 잔량")),
                ("drum_k", models.IntegerField(default=100, help_text="블랙 드럼 잔량")),
                ("toner_c_max", models.IntegerField(default=100)),
                ("toner_m_max", models.IntegerField(default=100)),
                ("toner_y_max", models.IntegerField(default=100)),
                ("toner_k_max", models.IntegerField(default=100)),
                ("toner_k2_max", models.IntegerField(default=100)),
                ("toner_recovery_max", models.IntegerField(default=100)),
                ("drum_c_max", models.IntegerField(default=100)),
                ("drum_m_max", models.IntegerField(default=100)),
                ("drum_y_max", models.IntegerField(default=100)),
                ("drum_k_max", models.IntegerField(default=100)),
                (
                    "manufacturer",
                    models.CharField(blank=True, help_text="제조사", max_length=256, null=True),
                ),
                (
                    "source",
                    models.CharField(default="agent", help_text="수집 출처", max_length=256),
                ),
                ("email_updated_at", models.DateTimeField(blank=True, null=True)),
                ("agent_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_data",
                        to="accounts.workplace",
                    ),
                ),
                (
                    "monitoring_printer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_data",
                        to="accounts.monitoringprinter",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_data",
                "unique_together": {("workplace", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="SuppliesAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                ("toner_c", models.IntegerField(default=100)),
                ("toner_m", models.IntegerField(default=100)),
                ("toner_y", models.IntegerField(default=100)),
                ("toner_k", models.IntegerField(default=100)),
                ("toner_k2", models.IntegerField(default=100)),
                ("toner_recovery", models.IntegerField(default=100)),
                ("drum_c", models.IntegerField(default=100)),
                ("drum_m", models.IntegerField(default=100)),
                ("drum_y", models.IntegerField(default=100)),
                ("drum_k", models.IntegerField(default=100)),
                ("toner_c_max", models.IntegerField(default=100)),
                ("toner_m_max", models.IntegerField(default=100)),
                ("toner_y_max", models.IntegerField(default=100)),
                ("toner_k_max", models.IntegerField(default=100)),
                ("toner_k2_max", models.IntegerField(default=100)),
                ("toner_recovery_max", models.IntegerField(default=100)),
                ("drum_c_max", models.IntegerField(default=100)),
                ("drum_m_max", models.IntegerField(default=100)),
                ("drum_y_max", models.IntegerField(default=100)),
                ("drum_k_max", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies_alerts",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "supplies",
                "unique_together": {("workplace", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="UnregisteredPrinter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_no", models.CharField(help_text="시리얼번호", max_length=256)),
                (
                    "confirmed_serial_no",
                    models.CharField(
                        blank=True, help_text="확인된 시리얼번호", max_length=256, null=True
                    ),
                ),
                (
                    "scanned_model",
                    models.CharField(
                        blank=True, help_text="스캔된 모델명", max_length=256, null=True
                    ),
                ),
                (
                    "printer_id",
                    models.BigIntegerField(blank=True, help_text="프린터 모델 FK", null=True),
                ),
                (
                    "customer_id",
                    models.BigIntegerField(blank=True, help_text="고객사 FK", null=True),
                ),
                (
                    "ip",
                    models.CharField(blank=True, help_text="IP 주소", max_length=256, null=True),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="위치", max_length=256, null=True),
                ),
                ("registered", models.BooleanField(default=False, help_text="등록 완료 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unregistered_printers",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "unregistered_printers",
                "unique_together": {("workplace", "serial_no")},
            },
        ),
    ]
