# Generated by Django 5.1.5 on 2026-08-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_oidlistmaster_monitoringprinter_printermodelmaster_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unregisteredprinter",
            unique_together={("workplace", "ip")},
        ),
    ]
