# Generated by Django 5.1.5 on 2026-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_unregisteredprinter_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="unregisteredprinter",
            name="count_color",
            field=models.IntegerField(default=0, help_text="탐지된 컬러 카운터"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="count_mono",
            field=models.IntegerField(default=0, help_text="탐지된 흑백 카운터"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="count_total",
            field=models.IntegerField(default=0, help_text="탐지된 총 카운터"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="last_scanned_at",
            field=models.DateTimeField(blank=True, help_text="최근 탐지 시각", null=True),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="mac_address",
            field=models.CharField(blank=True, help_text="MAC 주소", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="toner_c",
            field=models.IntegerField(default=0, help_text="C 토너 잔량 (%)"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="toner_k",
            field=models.IntegerField(default=0, help_text="K 토너 잔량 (%)"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="toner_m",
            field=models.IntegerField(default=0, help_text="M 토너 잔량 (%)"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="toner_y",
            field=models.IntegerField(default=0, help_text="Y 토너 잔량 (%)"),
        ),
        migrations.AddField(
            model_name="unregisteredprinter",
            name="vendor_name",
            field=models.CharField(
                blank=True, help_text="제조사명 (Fujifilm/Canon/HP 등)", max_length=120, null=True
            ),
        ),
    ]
