# Generated by Django 5.1.5 on 2026-08-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_unregisteredprinter_count_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempOidListMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, help_text="제조사", max_length=256, null=True),
                ),
                (
                    "printer_model",
                    models.CharField(
                        blank=True, help_text="프린터 모델명", max_length=256, null=True
                    ),
                ),
                (
                    "scanned_ip",
                    models.CharField(blank=True, help_text="스캔된 IP", max_length=256, null=True),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, help_text="시리얼 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "count1",
                    models.CharField(
                        blank=True, help_text="컬러 카운트 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "count2",
                    models.CharField(
                        blank=True, help_text="흑백 카운트 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "count3",
                    models.CharField(
                        blank=True, help_text="큰컬러 카운트 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "count3_k",
                    models.CharField(
                        blank=True, help_text="큰흑백 카운트 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "count4",
                    models.CharField(
                        blank=True, help_text="전체 카운트 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "toner_c",
                    models.CharField(
                        blank=True, help_text="시안 토너 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "toner_m",
                    models.CharField(
                        blank=True, help_text="마젠타 토너 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "toner_y",
                    models.CharField(
                        blank=True, help_text="옐로 토너 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "toner_k",
                    models.CharField(
                        blank=True, help_text="블랙 토너 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "toner_recovery",
                    models.CharField(
                        blank=True, help_text="회수 토너 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "drum_c",
                    models.CharField(
                        blank=True, help_text="시안 드럼 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "drum_m",
                    models.CharField(
                        blank=True, help_text="마젠타 드럼 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "drum_y",
                    models.CharField(
                        blank=True, help_text="옐로 드럼 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "drum_k",
                    models.CharField(
                        blank=True, help_text="블랙 드럼 OID 후보", max_length=256, null=True
                    ),
                ),
                (
                    "raw_walk_dump",
                    models.JSONField(blank=True, default=dict, help_text="Raw MIB Tree Dump JSON"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "검증 대기"),
                            ("CONFIRMED", "마스터 이관 완료"),
                            ("REJECTED", "거절됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_oid_lists",
                        to="accounts.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "temp_oid_lists",
                "ordering": ["-created_at"],
            },
        ),
    ]
