# Generated by Django 5.1.5 on 2026-08-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_tempoidlistmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcollector",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="매칭된 사업장 하위 특정 고객사",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collectors",
                to="accounts.monitoringcustomer",
            ),
        ),
    ]
