# Generated by Django 5.1.5 on 2026-08-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_agentcollector_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringcustomer",
            name="name",
            field=models.CharField(default="고객사", help_text="고객사명", max_length=120),
        ),
    ]
