# Generated by Django 5.1.5 on 2026-08-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_monitoringcustomer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolemenupermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("HEADQUARTERS", "본사 총괄 관리자"),
                    ("OWNER", "관리자(대표)"),
                    ("ADMIN_STAFF", "관리자(사무직원)"),
                    ("SALES", "영업"),
                    ("CE", "CE"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("HEADQUARTERS", "본사 총괄 관리자"),
                    ("OWNER", "관리자(대표)"),
                    ("ADMIN_STAFF", "관리자(사무직원)"),
                    ("SALES", "영업"),
                    ("CE", "CE"),
                ],
                default="CE",
                max_length=15,
            ),
        ),
    ]
