# Generated by Django 5.1.5 on 2026-08-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_rolemenupermission_role_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplyusage",
            name="monitoring_printer",
        ),
        migrations.RemoveField(
            model_name="supplyusage",
            name="workplace",
        ),
        migrations.DeleteModel(
            name="PrinterModelMaster",
        ),
        migrations.DeleteModel(
            name="SupplyUsage",
        ),
    ]
