# Generated by Django 5.1.5 on 2026-08-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_supplyusage_monitoring_printer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrinterOidMapping",
        ),
    ]
