# Generated by Django 5.1.5 on 2026-08-19 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_delete_printeroidmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prompt_intent", models.CharField(help_text="프롬프트 의도 요약", max_length=255)),
                ("ai_response", models.TextField(help_text="AI 응답 요약 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_chat_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "technician_name",
                    models.CharField(help_text="정비 담당 CE 성함", max_length=100),
                ),
                ("inspection_notes", models.TextField(help_text="점검 내용 및 교체 부품 코멘트")),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="accounts.printerasset",
                    ),
                ),
            ],
            options={
                "db_table": "device_maintenance_records",
                "ordering": ["-inspected_at"],
            },
        ),
    ]
