# Generated by Django 5.1.5 on 2026-08-20 03:47

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_aichatlog_devicemaintenancerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="backup_codes",
            field=accounts.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=accounts.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
