# Generated by Django 5.1.5 on 2026-08-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_backup_codes_alter_user_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="oidlistmaster",
            name="sys_object_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SNMP Enterprise sysObjectID (예: 1.3.6.1.4.1.2988)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tempoidlistmaster",
            name="sys_object_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SNMP Enterprise sysObjectID",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="oidlistmaster",
            index=models.Index(fields=["sys_object_id"], name="oid_lists_sys_obj_3e21e9_idx"),
        ),
        migrations.AddIndex(
            model_name="oidlistmaster",
            index=models.Index(
                fields=["manufacturer", "printer_model"], name="oid_lists_manufac_0e528a_idx"
            ),
        ),
    ]
